---
title: "compare"
author: "Yuchen Zeng"
date: "2019/3/27"
output: html_document
---

```{r}
rm(list=ls())

package = FALSE
draw=TRUE
run=TRUE

if(!require("clues")){
    install.packages("clues")
    stopifnot(require("clues"))
  }
require("tensorsparse")

if (package == TRUE){
  require("sparseBCnew")
} else {
  source('~/办公/课程/lab/mycode/main/sparseBC.R')
}

```


```{r}

method = "L0"


set.seed(100)
n = 200; p = 200; q = 1; k = 4; r = 5; l = 1
data = get.data(n,p,q,k,r,l,error=1,sort=TRUE,sparse.percent=0.7,mumin=-4,mumax=4)
test = data$x
truth = data$truthX
truthCs = data$truthCs
truthDs = data$truthDs
truthEs = data$truthEs
mus = data$mus
binaryX = data$binaryX

lambda_0 =c(floor(n*p*q/k/r/l))

if (method == "L0") lambda = (n*p*q)/(k*r*l)*seq(0,2,by=0.05)
if (method == "L1") lambda = (n*p*q)/(k*r*l)*seq(0,2,by=0.05)
```


```{r}
verlam = chooseLambda(test,k,r,l,lambda=lambda,method=method)
cat("the lambda tensorsparse choose is", verlam$lambda,".\n")
cat("the nonzeromus calculated by tensorsparse is ", verlam$nonzeromus, ".\n")
```

```{r}
splam = sparseBC.BIC(test[,,1],k,r,lambda = lambda)
cat("the lambda sparseBC choose is ", splam$lambda, ".\n")
cat("the nonzeromus calculated by sparseBC is ", splam$nonzeromus, ".\n")
```
```{r}
plot(lambda,verlam$BIC,pch=16,col="pink",ylim=c(min(c(verlam$BIC,splam$BIC)),max(c(verlam$BIC,splam$BIC))))
points(lambda,splam$BIC,pch=17,col="lightblue")
```

```{r}
t.sim = classify2(test,k,r,1,lambda=verlam$lambda,trace=FALSE,method=method,center=FALSE)


if(draw==TRUE){
  plot_tensor(test)
  Sys.sleep(0.5)
  
  plot_tensor(truth)
  Sys.sleep(0.5)
  
  plot_tensor(t.sim$judgeX)
}

cat("The result of with the lambda tensorsparse choose:\n")
sparse.evaluate(t.sim,data)
```

```{r}
s.sim = sparseBC(test[,,1],k,r,lambda=splam$lambda,center=FALSE)
s.sim$judgeX = array(c(s.sim$mus),dim=c(200,200,1))

if (draw == TRUE){
  plot_tensor(test)
  Sys.sleep(0.5)
  
  plot_tensor(truth)
  Sys.sleep(0.5)
  plot_tensor(s.sim$judgeX)
}



cat("The result of with the lambda sparseBC choose:\n")
sparse.evaluate(s.sim,data)
```

```{r}
if(run==FALSE) stop("End.")
tc = classify2(test,4,5,1,threshold=1e-10,lambda=verlam$lambda,trace=FALSE,method=method)
mc = sparseBC(test[,,1],4,5,lambda=verlam$lambda,center = FALSE,method=method)

similarityC<-adjustedRand(tc$Cs,mc$Cs,randMethod=c("Rand"))
similarityD<-adjustedRand(tc$Ds,mc$Ds,randMethod=c("Rand"))
cat("The similarity of two clustering result is ",similarityC,",",similarityD,".\n")

tcBIC = tensor.calculateBIC(test,tc,method=method)
mcBIC = CalculateBIC(test[,,1],mc,method=method)
cat("The BIC calculated by tensorsparse is", tcBIC, ", the BIC calculated by sparseBC is", mcBIC, ".\n")
```


```{r}
tc = classify2(test,4,5,1,threshold=1e-10,lambda=splam$lambda,trace=FALSE,method=method)
mc = sparseBC(test[,,1],4,5,lambda=splam$lambda,center = FALSE,method=method)

similarityC<-adjustedRand(tc$Cs,mc$Cs,randMethod=c("Rand"))
similarityD<-adjustedRand(tc$Ds,mc$Ds,randMethod=c("Rand"))
cat("The similarity of two clustering result is ",similarityC,",",similarityD,".\n")

tcBIC = tensor.calculateBIC(test,tc,method=method)
mcBIC = CalculateBIC(test[,,1],mc,method=method)
cat("The BIC calculated by tensorsparse is", tcBIC, ", the BIC calculated by sparseBC is", mcBIC, ".\n")
```


```{r}
lambda = 2000
tc = classify2(test,4,5,1,lambda=lambda,trace=FALSE,method=method)
mc = sparseBC(test[,,1],4,5,lambda=lambda,method=method)

similarityC<-adjustedRand(tc$Cs,mc$Cs,randMethod=c("Rand"))
similarityD<-adjustedRand(tc$Ds,mc$Ds,randMethod=c("Rand"))
cat("When lambda =", lambda, ":\n")
cat("The similarity of two clustering result is ",similarityC,",",similarityD,".\n")

tcBIC = tensor.calculateBIC(test,tc,method=method)
mcBIC = CalculateBIC(test[,,1],mc,method=method)
cat("The BIC calculated by tensorsparse is", tcBIC, ", the BIC calculated by sparseBC is", mcBIC, ".\n")
```











